linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Wrap(
      - errors.WrapContext(
      - errors.WithContext(
      - errors.WithMetadata(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      # gRPC errors
      - status.Error(
      - status.Errorf(
      - contexts.WrapSpanError
      - contexts.SpanError
      - contexts.SpanErrorf

  gofmt:
    simplify: true

  misspell:
    locale: UK

  paralleltest:
    # Ignore missing calls to `t.Parallel()` and only report incorrect uses of it.
    ignore-missing: true

linters:
  enable:
    - bodyclose
    - gosec
    - whitespace
    - unconvert
    - wrapcheck
    - revive
    - gocritic
    - gomoddirectives
    - gofmt
    - gofumpt
    - misspell
    - gosec
    - paralleltest
    - importas
    - durationcheck
    - errcheck
  presets:
    - unused
    - bugs

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - bodyclose
        - gosec
        - unused
