linters-settings:
  wrapcheck:
    ignoreSigs:
    - .Errorf(
    - errors.New(
    - errors.Wrap(
    - errors.WrapContext(
    - errors.WithContext(
    - errors.WithMetadata(
    - .Wrap(
    - .Wrapf(
    - .WithMessage(
    - .WithMessagef(
    - .WithStack(
    # gRPC errors
    - status.Error(
    - status.Errorf(
